### ISSUE TITLE
Aws Glue has no list_blueprints: aws cli and boto3 issue

### ISSUE THREAD

**Issue by iamtodor** [awsdocs/aws-glue-developer-guide#70]
Hello,

I've followed the instructions https://docs.aws.amazon.com/en_us/glue/latest/dg/developing-blueprints-prereq.html#prereqs-setup-cli

In my terminal I run the following command: `aws glue list-blueprints --region eu-central-1`
The output is
```
aws: error: argument operation: Invalid choice, valid choices are:
```

My aws cli
```
aws --version
>>> aws-cli/2.1.39 Python/3.8.8 Darwin/20.3.0 exe/x86_64 prompt/off
```

The same I get with python code
```python
import boto3

glue = boto3.client('glue', 'eu-central-1')

if __name__ == '__main__':
    print(glue.list_blueprints())
```

The output
```
AttributeError: 'Glue' object has no attribute 'list_blueprints'
```

libs are
```
boto3==1.17.31
botocore==1.20.31
```

What am I missing?

**Comment by janetst** [comment]
I get the same ... -list-blueprints is not shown as a valid command. This is mostly likely due to the fact that the feature is not generally available yet. 

https://docs.aws.amazon.com/glue/latest/dg/blueprints-overview.html - Notice the banner that says "The AWS Glue blueprints feature is in preview release for AWS Glue and is subject to change. "

**Comment by iamtodor** [comment]
@janetst I see. Thank you :)
